//
//  DataProvider.swift
//  pauls100MiniProjects
//
//  Created by Paul Pires on 19/02/2018.
//  Copyright © 2018 Paul Pires. All rights reserved.
//

import UIKit

class DataProvider {
    
    func projects() -> [ProjectViewModel] {

        return [
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip"),
            Project(name: "wip", imageName: "wip"),
            Project(name: "wip2", imageName: "wip"),
            Project(name: "wip3", imageName: "wip"),
            Project(name: "wip4", imageName: "wip"),
            Project(name: "wip5", imageName: "wip")
        ].map {
            return ProjectViewModel(projectModel: $0)
        }
    }
}
